nimble:
  server:
    port: 7905

  spring:
    application:
      name: gateway

  eureka:
    client:
      service-url:
        defaultZone: http://eureka1:7901/eureka,http://eureka2:7902/eureka
    instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${server.port}

  zuul:
    host:
      connect-timeout-millis: 10000
      socket-timeout-millis: 60000
    ignored-services: provider
    routes:
      user:
        path: /user/**
        service-id: consumer

  logging:
    level:
      root: info
